version: 2
updates:

- package-ecosystem: maven
  directory: /
  ignore:
  - update-types: [version-update:semver-major]
    dependency-name: '*'
  schedule:
    interval: weekly
#
#- package-ecosystem: gitsubmodule
#  directory: /
#  schedule:
#    interval: weekly
