name: Generate Documentation with JavaDoc
on:
  push:
    paths:
    - .github/workflows/documentation.yml
    - src/main/**
    - pom.xml
  pull_request:
    paths:
    - .github/workflows/documentation.yml
    - src/main/**
    - pom.xml
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'
        cache: maven
    
    - name: Package JavaDoc
      run: mvn -batch-mode javadoc:javadoc
      env: {GITHUB_TOKEN: "${{ github.token }}"}
    
    - uses: actions/upload-pages-artifact@v3
      with:
        path: target/site/apidocs
  
  deploy:
    needs: build
    if: github.ref_name == 'main'
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    
    - uses: actions/configure-pages@v5
    
    - id: deploy-pages
      uses: actions/deploy-pages@v4
