name: Generate Documentation with JavaDoc
on:
  push:
    branches: [main]
    paths: [.github/workflows/documentation.yml, src/main/java/**]
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - uses: actions/configure-pages@v3
    
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'
        cache: maven
    
    - name: Package JavaDoc
      run: mvn -batch-mode javadoc:javadoc
      env: {GITHUB_TOKEN: "${{ github.token }}"}
    
    - uses: actions/upload-pages-artifact@v2
      with:
        path: target/site/apidocs
  
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - id: deploy-pages
      uses: actions/deploy-pages@v4
