name: Test with Maven
on:
  push:
    paths: [.github/workflows/test.yml, src/**]
  pull_request:
    paths: [.github/workflows/test.yml, src/**]
jobs:
  
  spec:
    strategy:
      fail-fast: false
      matrix:
        java-version: ['20', '17', '11', '8']
    name: 'Java ${{ matrix.java-version }}'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java-version }}
        cache: maven
    
    - name: Test with Maven
      run: mvn -batch-mode test
      env: {GITHUB_TOKEN: "${{ github.token }}"}
