name: Test with Maven
on:
  push:
    paths: [.github/workflows/test.yml, src/**, pom.xml]
  pull_request:
    paths: [.github/workflows/test.yml, src/**, pom.xml]
jobs:
  
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: ['21', '17']
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
    
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java-version }}
        cache: maven
    
    - name: Test with Maven
      run: mvn -batch-mode test
      env: {GITHUB_TOKEN: "${{ github.token }}"}
